### PR TITLE
A few formatting fixes for CSS style guide

### PR DESCRIPTION
**Pull request by jeremiak**
@msecret here are just a couple of formatting things I saw on the new CSS style guide. 

These minor things aside - it's **awesome**, nice work!

### CODE REVIEW

**Comment by msecret** [comment]
Sorry I probably messed you up because I switched the main branch on this repo from master to 18f-pages-staging and committed something to it. Let me know if you need help fixing merge conflicts.

**Comment by meiqimichelle** [comment]
Ping! Any chance someone has a few minutes to resolve? That sub-nav is too beautiful to be left un-merged ;)

**Comment by meiqimichelle** [comment]
Ping @jeremiak -- any chance you can resolve this and merge?

**Comment by jeremiak** [comment]
No longer necessary

**Pull request closed without merging**
