### PR TITLE
Typo in Backbone framework cons

### PR DESCRIPTION
**Pull request by jeffmaher**
Small typo. "Files changed" (diff) shows the change clearly.

### CODE REVIEW

**Comment by tbaxter-18f** [comment]
While you're at it, should it be "inexperienced"?

**Comment by jeffmaher** [comment]
@tbaxter-18f : Ha! I Googled for this too, but looks like Merriam Webster says "unexperienced" is a synonym for "inexperienced," so I just left it. 😄 

https://www.merriam-webster.com/dictionary/unexperienced

**Comment by tbaxter-18f** [comment]
I wonder if more folks will trip over it wondering if it's wrong. Maybe we should ask a content person?

**Comment by jeffmaher** [comment]
I'm cool with changing it if it'll make it clearer (since "inexperienced" will mean the same thing and it sounds cleaner). Commit coming right up...

**Comment by tbaxter-18f** [comment]
Thanks. LGTM.

**Review by xtine — APPROVED** [review]
Thanks for this correction.

**Pull request merged**
