### PR TITLE
[WIP] restructure -> production

### PR DESCRIPTION
**Pull request by shawnbot**
[:sunglasses: Preview on Federalist](https://federalist.18f.gov/preview/18F/frontend/18f-pages-staging/)

This PR will merge the new single-document structure (described in #96, mostly implemented in #97) to the `18f-pages` branch and publish it to the [live URL](https://pages.18f.gov/frontend/).

Before we do this, let's get some eyes on it! A couple of things need to be addressed before we can merge:
- [x] address merge conflicts
- [x] fix sidebar height issue: #111 
- [x] emoji vote on whether the "Technical Guides" menu nesting is appropriate, since there isn't anything else at the top level
- [x] the section heading font sizes are all wonky #133

Please add to this list if you see anything else glaringly broken!

### CODE REVIEW

**Comment by msecret** [comment]
Created #133 to track the heading size issue

**Comment by juliasolorzano** [comment]
Friendly reminder, we will most likely be fixing the merge conflicts directly and this will make that merge happen auto-magically. Should be the last thing we do before merging in 😄

**Comment by msecret** [comment]
So we now fixed the heading issues, which means we should get this out. Do we need to fix these merge conflicts, or should we just go for a force push? @shawnbot @juliaelman

**Comment by juliasolorzano** [comment]
Merge conflicts are now resolved and we're going live! 🎉 to everyone for your work on this!!

**Pull request merged**
