### PR TITLE
Use guides_style_18f gem

### PR DESCRIPTION
**Pull request by mbland**
cc: @meiqimichelle @msecret

### CODE REVIEW

**Comment by mbland** [comment]
Ping...? Also, you'd get two PRs for the price of one here: The commit I just pushed to incorporate changes from 18F/guides-style#1 would obsolete #34.

**Comment by meiqimichelle** [comment]
@mbland This didn't run properly locally for me and I don't have time to debug right now :-/

**Comment by mbland** [comment]
You're probably not seeing the styles applied, correct? You need to comment out the `asset_root:` attribute in `_config.yml`. Should run fine after that.

Yes, this sucks, but the intention is that the production instance will get style updates from `https://pages.18f.gov/guides-template/`: hence the setting of `asset_root: /guides-template`.

That said, I'm [testing and refactoring 18F pages](https://github.com/18F/pages/pull/19), and once that's done (hopefully today), I plan to implement a feature to apply a server-specific config on the server-side, per Eric's suggestion in 18F/pulse#270. Once that's done, `asset_root:` can go away from this `_config.yml`.

However, it's hard to say how soon I'll be able to roll that out. Consequently, I'd suggest merging sooner than later, but i'll be sending a volley of quick follow-up PRs once that feature is in-place.

**Comment by meiqimichelle** [comment]
We've made some changes in the frontend guide to our styles -- the most important being those for the accordion subnav. Are those in the `/guides-template` ?

**Comment by mbland** [comment]
Not yet... I see a few differences:

```
$ diff guides-style/lib/guides_style_18f/sass/_guides_style_18f_main.scss frontend/assets/css/main.css
0a1,3
> ---
> ---
> 
171,174c174
<   padding-bottom: 10px;
<   padding-right: 10px;
<   padding-left: 14px;
<   padding-top: 10px;
---
>   padding: 10px;
193c193
<   border-left: 4px solid #1188ff;
---
>   border-left: 4px solid {{ site.brand_color }};
205a206
>   padding-left: 4px;
325c326
<     border-bottom: 4px solid #1188ff;
---
>     border-bottom: 4px solid {{ site.brand_color }};
525,528d525
<     .main-content img {
<         max-width: 100%;
<     }
< 
```

The `{{ site.brand_color }}` styles changes don't matter, as it makes sense for `#1188ff` to be hardcoded for `guides_style_18f`. The other differences are very minor. I can either put those differences into this PR, or maybe we can backport them into the `guides_style_18f` gem, if they'd be useful for other Guides.. Which would you prefer?

**Comment by meiqimichelle** [comment]
I think the sub-nav work would be useful for other folks, too. I'm sorry I don't have more time to review thoroughly to make sure things port correctly! @noahmanger implemented the nav, maybe he has a few minutes to make sure things go well when you bring over to the gem.

**Comment by noahmanger** [comment]
I don't have strong feelings. As far as I recall, the other changes just tweaked a few things on the way the nav was styled.

**Comment by mbland** [comment]
OK, I'll add it to the gem, cut 0.0.2, update this PR, and ping when ready.

**Comment by mbland** [comment]
Updated this with the latest `guides_style_18f` and `go_script` hotness. Now you can run locally at http://localhost:4000/, still publish automatically to https://pages.18f.gov/frontend/, and all the styles look right without any `baseurl:` or `asset_root:` tricks. As a bonus, now the sidebar works the way it should, staying open on child pages and highlighting the proper element. Plus, thanks to the `./go update_nav` command, I discovered a `Recommended dependencies` page that wasn't there before:d

after

**Comment by mbland** [comment]
Ping...

**Comment by msecret** [comment]
@meiqimichelle does this look good? It looks fine to me.

**Comment by mbland** [comment]
FYI, taking care of merge conflicts now.

**Comment by mbland** [comment]
OK, this is good to go now. Looks good locally. Also tweaked title capitalization per https://pages.18f.gov/content-guide/capitalization/.

**Comment by mbland** [comment]
Ping...

**Comment by meiqimichelle** [comment]
@shawnbot said it looks good to him, and I also just pulled and it ran just fine and looks good, so..... :mouse: :boom: ! Thank you @mbland !

**Comment by mbland** [comment]
Yay, thanks, @meiqimichelle! :smile:

**Pull request merged**
